### ISSUE TITLE
error on python generator.py

### ISSUE THREAD

**Issue by Spit-fires** [avengy/Discord-Tokens-Generator#23]
```
Exception in thread Thread-94 (manager):
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/httpcore/backends/sync.py", line 57, in start_tls
    raise exc
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/httpcore/backends/sync.py", line 52, in start_tls
    sock = ssl_context.wrap_socket(
  File "/data/data/com.termux/files/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/data/data/com.termux/files/usr/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/data/data/com.termux/files/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: _ssl.c:980: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request
    raise exc
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 86, in handle_request
    raise exc
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 150, in _connect
    stream = stream.start_tls(**kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/httpcore/backends/sync.py", line 49, in start_tls
    with map_exceptions(exc_map):
  File "/data/data/com.termux/files/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectTimeout: _ssl.c:980: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/data/data/com.termux/files/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/data/data/com.termux/files/home/downloads/Discord-Tokens-Generator/generator.py", line 154, in manager
    register(invitecode)
  File "/data/data/com.termux/files/home/downloads/Discord-Tokens-Generator/generator.py", line 50, in register
    getcookie = httpx.get("https://discord.com/register").headers['set-cookie']
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/httpx/_api.py", line 189, in get
    return request(
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/httpx/_api.py", line 100, in request
    return client.request(
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/httpx/_client.py", line 815, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/httpx/_client.py", line 902, in send
    response = self._send_handling_auth(
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/httpx/_client.py", line 930, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/httpx/_client.py", line 967, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/httpx/_client.py", line 1003, in _send_single_request
    response = transport.handle_request(request)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 217, in handle_request
    with map_httpcore_exceptions():
  File "/data/data/com.termux/files/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: _ssl.c:980: The handshake operation timed out```
```

**Comment by yezysarered** [comment]
don't use termux you dumb bitch
