### ISSUE TITLE
Hey mate

### ISSUE THREAD

**Issue by NoCPS** [avengy/Discord-Tokens-Generator#5]
Where is the link to the hcaptcha bypass repo? Mind dropping it below please?

**Comment by NoCPS** [comment]
Nvm I'm dumb I figured it out

**Comment by Locksdsc** [comment]
threads to use:4
CAPTCHA KEY IS >>>>:  False
CAPTCHA KEY IS >>>>:  False
CAPTCHA KEY IS >>>>:  False
CAPTCHA KEY IS >>>>:  False
Exception in thread Thread-2:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\L.L\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_sync\http_proxy.py", line 227, in _tunnel_request
Traceback (most recent call last):
  File "C:\Users\L.L\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_sync\http_proxy.py", line 227, in _tunnel_request
    ) = proxy_connection.handle_request(
    ) = proxy_connection.handle_request(
  File "C:\Users\L.L\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_sync\connection.py", line 136, in handle_request
  File "C:\Users\L.L\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_sync\connection.py", line 136, in handle_request
    self.socket = self._open_socket(timeout)
    self.socket = self._open_socket(timeout)
  File "C:\Users\L.L\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_sync\connection.py", line 163, in _open_socket
  File "C:\Users\L.L\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_sync\connection.py", line 163, in _open_socket
    return self._backend.open_tcp_stream(
    return self._backend.open_tcp_stream(
  File "C:\Users\L.L\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_backends\sync.py", line 144, in open_tcp_stream
  File "C:\Users\L.L\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_backends\sync.py", line 144, in open_tcp_stream
    return SyncSocketStream(sock=sock)
    return SyncSocketStream(sock=sock)
  File "C:\Users\L.L\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
  File "C:\Users\L.L\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\L.L\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    self.gen.throw(type, value, traceback)
  File "C:\Users\L.L\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
    raise to_exc(exc) from None
httpcore.ConnectTimeout: timed out
httpcore.ConnectTimeout: timed out

During handling of the above exception, another exception occurred:


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\L.L\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_transports\default.py", line 61, in map_httpcore_exceptions
  File "C:\Users\L.L\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_transports\default.py", line 61, in map_httpcore_exceptions
    yield
  File "C:\Users\L.L\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_transports\default.py", line 180, in handle_request
    yield
    status_code, headers, byte_stream, extensions = self._pool.handle_request(
  File "C:\Users\L.L\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_transports\default.py", line 180, in handle_request
  File "C:\Users\L.L\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_sync\http_proxy.py", line 127, in handle_request
    status_code, headers, byte_stream, extensions = self._pool.handle_request(

**Comment by cChimney** [comment]
It doesn't work anymore lmfao you gotta change the code to make it work + get better proxies than this
